INSERT INTO usuariosGestion(nombre,nick,pass) VALUES ("daniel","dani","dani");
INSERT INTO usuariosGestion(nombre,nick,pass) VALUES ("javier","javi","javi");

INSERT INTO solicitudes (dni,razonSocial,domicilioSocial,ciudad,email,telefono,nick,pass) VALUES("11111111H","pepito2 S.A.","Avenida de pepito2 n 7","Alicante","pepito2@pepito2.com","987654321","pepito2","pepito2");
INSERT INTO solicitudes (dni,razonSocial,domicilioSocial,ciudad,email,telefono,nick,pass) VALUES("22222222J","juani2 S.A.","Calle del profesor n 12","Santa Pola","juani2@juani2.com","963852741","juani2","juani2");
INSERT INTO solicitudes (dni,razonSocial,domicilioSocial,ciudad,email,telefono,nick,pass) VALUES("33333333P","dani2 S.L.","Avenida de dani2el n 3","Elche","dani2@dani2.com","986753421","dani2","dani2");
INSERT INTO solicitudes (dni,razonSocial,domicilioSocial,ciudad,email,telefono,nick,pass) VALUES("44444444A","fran2 S.L.","Avenida de San fran2cisco","Valverde","fran2@fran2.com","951738624","fran2","fran2");
INSERT INTO solicitudes (dni,razonSocial,domicilioSocial,ciudad,email,telefono,nick,pass) VALUES("44444444A","javi S.L.","Avenida de San javi2","Valverde","javi2@javi2.com","951738624","javi2","javi2");

INSERT INTO clientes (dni,razonSocial,domicilioSocial,ciudad,email,telefono,nick,pass,activo) VALUES("11111111H","Pepito S.A.","Avenida de pepito n 7","Alicante","pepito@pepito.com","987654321","pepito","pepito",1);
INSERT INTO clientes (dni,razonSocial,domicilioSocial,ciudad,email,telefono,nick,pass,activo) VALUES("22222222J","Juani S.A.","Calle del profesor n 12","Santa Pola","juani@juani.com","963852741","juani","juani",1);
INSERT INTO clientes (dni,razonSocial,domicilioSocial,ciudad,email,telefono,nick,pass,activo) VALUES("33333333P","Dani S.L.","Avenida de daniel n 3","Elche","dani@dani.com","986753421","dani","dani",1);
INSERT INTO clientes (dni,razonSocial,domicilioSocial,ciudad,email,telefono,nick,pass,activo) VALUES("44444444A","Fran S.L.","Avenida de San Francisco","Valverde","fran@fran.com","951738624","fran","fran",1);
INSERT INTO clientes (dni,razonSocial,domicilioSocial,ciudad,email,telefono,nick,pass,activo) VALUES("44444444A","javi S.L.","Avenida de San javi","Valverde","javi@javi.com","951738624","javi","javi",1);


INSERT INTO articulos(img,nombre,descripcion,precio,descuento) VALUES ("vista/img/articulos/ztebladev6.png","Blade V6","Un auténtico pura sangre.<br><br>Así es como han denominado a este titán de la tecnología.<br><br>El ZTE V6 es un teléfono con tecnología 4G de 5 pulgadas con Dual Sim para que siempre estés conectado y a la máxima velocidad.<br><br>Con un procesador Mediatek MT6735 con arquitectura de 64bits, podrás jugar a tus juegos favoritos y navegar por internet de manera veloz y fluida.","89","37");
INSERT INTO articulos(img,nombre,descripcion,precio,descuento) VALUES ("vista/img/articulos/XiaomiRedmi4x.jpg","Redmi 4x","Te presentamos el Xiaomi Redmi 4X,  un smpartphone barato con 3 GB de RAM y 32 GB de almacenamiento interno.","149","0");
INSERT INTO articulos(img,nombre,descripcion,precio,descuento) VALUES ("vista/img/articulos/huawei-p9-lite-negro.jpg","P9 Lite","El smartphone Huawei P9 3GB Lite blanco es el nuevo miembro de la familia Huawei, la marca de móviles libres que se ha hecho un hueco en el mercado gracias a su buen hacer, móviles de calidad y excelente relación calidad/precio.<br><br>Del P9 3GB Lite destaca el ratio cuerpo-pantalla, que llega en este móvil al 76.4% de la superficie frontal en forma de pantalla.<br><br>Una excelente pantalla que combina a la perfección con un atractivo y ergonómico diseño con un biselado metálico que actúa como marco de un dispositivo excelente en apariencia y especificaciones.","169","11");
INSERT INTO articulos(img,nombre,descripcion,precio,descuento) VALUES ("vista/img/articulos/sgj3-2.jpg","Galaxy J3 ","Con el Samsung Galaxy J3, la compañía surcoreana continúa la línea basada en ofrecer móviles baratos con especificaciones interesantes dentro de los smartphone de su gama.<br><br>En concreto, el Samsung J3 cuenta con una pantalla de 5 pulgadas AMOLED con resolución HD que cobra vida con un procesador Quad-Core a 1.2GHz y 1.5GB de RAM.<br><br>En cuanto al apartado de almacenamiento,  este móvil Samsung dispone de 8GB de almacenamiento que puedes ampliar con una tarjeta MicroSD de hasta 128GB.","119","8");
INSERT INTO articulos(img,nombre,descripcion,precio,descuento) VALUES ("vista/img/articulos/mmg5.jpg","Moto G5","Ten más por menos con el Moto G5.<br><br>No vuelvas a preocuparte por el almacenamiento.<br><br>El Moto G cuenta con 16 GB de memoria interna a la que puedes añadir fácilmente hasta 128 GB mediante una tarjeta microSD opcional.<br><br>Podrás disfrutar de una multitarea fluida con el rápido procesador de ocho núcleos y velocidad 4G.<br><br>Utilízalo todo el día con una sola carga y consigue horas de energía en solo minutos con el cargador rápido incluido.<br><br>Captura fotos brillantes con la cámara de 13 MP con enfoque rápido y PDAF, de forma que no te pierdas ni un momento especial.<br><br>Además, la cámara frontal gran angular de 5 MP no dejará a nadie fuera de los selfies de grupo.<br><br>Disfruta de todo esto en una pantalla Full HD de 5,0 pulgadas con los colores vivos y el excelente nivel de detalle que puedes encontrar en un teléfono de primera calidad.","189","0");
INSERT INTO articulos(img,nombre,descripcion,precio,descuento) VALUES ("vista/img/articulos/bqaup.jpg","Aquaris U","Con Aquaris U damos un paso más en el uso del metal, utilizándolo por primera vez en la parte trasera de uno de nuestros smartphones.<br><br>Sus líneas curvas no sólo son elegantes, además abrazan la pantalla para mejorar la ergonomía.<br><br>El proceso de fabricación comienza con un exhaustivo diseño mecánico y termina con un proceso de anodización y sandblasting del aluminio que nos ha permitido conseguir el color perfecto, una textura pulida y un tacto sensacional.<br><br>El resultado es un dispositivo muy ligero pero extremadamente resistente.<br><br>Características:","159","0");
INSERT INTO articulos(img,nombre,descripcion,precio,descuento) VALUES ("vista/img/articulos/apip6.jpeg","iPhone 6","Apple presentó iPhone 6s, y con él, toda una avalancha de novedades y funcionalidades maceradas, como siempre, con un espectacular diseño.<br><br>Una de las novedades más llamativas es su gran pantalla de 4.7 pulgadas.<br><br>Más sorprendente es que este aumento no repercuta en el grosor y el peso del dispositivo, que se mantienen en unas más que magníficas cifras: 6,9 mm y 129 gramos.<br><br>iPhone 6, el más fino de la historia","379","0");
INSERT INTO articulos(img,nombre,descripcion,precio,descuento) VALUES ("vista/img/articulos/honor-7x-blue-1-1.jpg","7X","Te presentamos el Honor 7X, el primer smartphone de Honor con pantalla infinita.","269","11");
INSERT INTO articulos(img,nombre,descripcion,precio,descuento) VALUES ("vista/img/articulos/lgxp.jpg","X Power","Más potencia, menos grosor.<br><br>Con tan solo 7,9mm de espesor a pesar de su potente batería de 4100mAh, el LG X Power combina a la perfección diseño y potencia.<br><br>No necesitas una batería extra.<br><br>La espectacular batería de 4100,mAh del LG X Power es más que suficiente para aguantar tu ritmo durante todo el día.","129","27");
INSERT INTO articulos(img,nombre,descripcion,precio,descuento) VALUES ("vista/img/articulos/bqau2l.jpg","Aquaris U2","Gracias a su batería LiPo de 3100 mAh y a una meticulosa selección de componentes de bajo consumo, sacarás todo el partido a tu Aquaris U2 sin tener que cargarlo constantemente.<br><br>Y con su carga rápida Qualcomm Quick Charge 3.0, pasará de 0 a 100 % de almacenamiento energético en un abrir y cerrar de ojos.<br><br>Haz que tus selfies brillen con luz propia gracias al flash frontal integrado, que da el toque de iluminación que necesitas para salir bien incluso de noche.<br><br>El modo Face Beauty hará el resto: detecta las caras y suaviza los rasgos para que desaparezcan las pequeñas imperfecciones.<br><br>Y con su cámara trasera con 8 MP y enfoque ultrarrápido, captarás tus momentos más especiales de forma ágil y nítida.<br><br>Con el procesador Qualcomm Snapdragon 425 y sus cuatro núcleos a 1,4 GHz, exprime tu contenido multimedia, chatea, navega por tus redes a toda velocidad o disfruta de todas las novedades que Android 8 Oreo traerá a tu Aquaris U2 Lite.","159","0");
INSERT INTO articulos(img,nombre,descripcion,precio,descuento) VALUES ("vista/img/articulos/iphone-x-silver-select-2017-av1.jpg","iPhone X","iPhone X,  un iPhone capaz de sumergirte por completo en lo que ves.<br><br>Y tan inteligente que responda a un toque, a tu voz, incluso a tu mirada.<br><br>Ahora el iPhone X hace realidad esa visión.<br><br>Dile hola al futuro.","1099","0");
INSERT INTO articulos(img,nombre,descripcion,precio,descuento) VALUES ("vista/img/articulos/wiko-ufeel-4g-16gb-gris-libre.jpg","UFeel","Te presentamos el fantástico smartphone UFeel 4G 16 GB de Wiko.<br><br>En tu mano, la mezcla de materiales y los colores más frescos.<br><br>Ufeel es la combinación definitiva de metal con un increíble efecto piedra de contrastes fuertes, y una pantalla 2.5D curva para darle un atractivo look premium.<br><br>Su brillante pantalla HD hace que tu experiencia multimedia sea de otro nivel.<br><br>¡Una gran cámara...<br><br>y sobre todo su sensor dactilar y la posibilidad de personalizar 5 huellas dactilares para 5 acciones diferentes! Asigna un uso específico para cada huella como, por ejemplo, llamar a tu madre o a tus mejores amigos, y haz tu experiencia realmente personal","109","0");
INSERT INTO articulos(img,nombre,descripcion,precio,descuento) VALUES ("vista/img/articulos/gpxl.jpg","Pixel XL ","Píxel es el primer teléfono inteligente con el Asistente de Google.<br><br>Tiene capacidad ilimitada de almacenamiento para todas tus fotos y videos, una batería que dura todo el día y una la cámara de un teléfono inteligente de las más valoradas.<br><br>El primer teléfono inteligente con Google Asistente Averiguar cuándo un museo cierra, lo que puedes hacer en la ciudad así como los cafés están disponibles en tu área.<br><br>La cámara del smartphone con mejor calificación","499","0");